In [2]:
import numpy as np

In [12]:
Z=np.array([[[34,44,5],[4,33,67]],[[12,437,6],[9,64,5]]])
Z

array([[[ 34,  44,   5],
        [  4,  33,  67]],

       [[ 12, 437,   6],
        [  9,  64,   5]]])

In [4]:
dim=0

In [5]:
Z.shape

(2, 2, 3)

In [6]:
Z_moved = np.moveaxis(Z, dim,-1)
original_shape = Z_moved.shape 

Z_moved

array([[[ 34,  12],
        [ 44, 437],
        [  5,   6]],

       [[  4,   9],
        [ 33,  64],
        [ 67,   5]]])

In [7]:
Z_moved.shape

(2, 3, 2)

In [13]:
Z

array([[[ 34,  44,   5],
        [  4,  33,  67]],

       [[ 12, 437,   6],
        [  9,  64,   5]]])

In [15]:
Z.swapaxes(0,-1)

array([[[ 34,  12],
        [  4,   9]],

       [[ 44, 437],
        [ 33,  64]],

       [[  5,   6],
        [ 67,   5]]])

In [45]:
key_padding_mask = np.array([[False, False, True, True],   # batch 0
                              [False, True,  True, True]])  # batch 1
# shape (2, 4) = (N=2, S=4)

key_mask = key_padding_mask[:,np.newaxis, np.newaxis,:]
# shape (2, 1, 1, 4) = (N=2, 1, 1, S=4)


In [46]:
key_mask

array([[[[False, False,  True,  True]]],


       [[[False,  True,  True,  True]]]])

In [37]:
key_mask2 = key_padding_mask[:, np.newaxis, np.newaxis, :]

In [43]:
key_mask2.shape

(2, 1, 1, 4)

In [38]:
key_mask

array([[[[False, False,  True,  True],
         [False,  True,  True,  True]]]])

In [39]:
key_mask2

array([[[[False, False,  True,  True]]],


       [[[False,  True,  True,  True]]]])

In [42]:
key_mask

array([[[[False, False,  True,  True],
         [False,  True,  True,  True]]]])

In [50]:
8//3

2

In [51]:
import torch

In [53]:
lengths = [3,2] 
T=5

In [54]:
N,T = 3,2

In [ ]:
positions = torch.arange(T,device=padded_input.device)

3

In [56]:
def PadMask(padded_input, input_lengths):
    N, T = padded_input.shape[0], padded_input.shape[1]
    # positions: (1, T) vs lengths: (N, 1) -> broadcasts to (N, T)
    positions = torch.arange(T, device=padded_input.device).unsqueeze(0)  # (1, T)
    lengths   = input_lengths.unsqueeze(1)                                  # (N, 1)
    return positions >= lengths  # True where padding


In [71]:
T = [[0, 1, 2, 3, 4]]
lengths = [[3],
           [2],
           [4]]


In [75]:
T= torch.arange(5)

In [ ]:
torch.arange(5).unsqueeze(1).

tensor([[0],
        [1],
        [2],
        [3],
        [4]])

In [78]:
T

tensor([0, 1, 2, 3, 4])

In [82]:
positions  = torch.arange(5).unsqueeze(0) 
print(positions)
print(positions.shape)

tensor([[0, 1, 2, 3, 4]])
torch.Size([1, 5])


In [85]:
lengths = torch.arange(3).unsqueeze(1)
print(lengths)
print(lengths.shape)

tensor([[0],
        [1],
        [2]])
torch.Size([3, 1])


In [96]:
pad_mask=positions>=lengths
pad_mask

tensor([[ True,  True,  True,  True,  True],
        [False,  True,  True,  True,  True],
        [False, False,  True,  True,  True]])

In [95]:
torch.triu(pad_mask, diagonal=1)

tensor([[False,  True,  True,  True,  True],
        [False, False,  True,  True,  True],
        [False, False, False,  True,  True]])

In [52]:
import torch
import math
d_model=10

In [53]:
max_length=5

In [54]:
positions = torch.arange(0, max_length).unsqueeze(1).float()
print(positions)

tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.]])


In [55]:
i = torch.arange(0, d_model, 2).float()
print(i)

tensor([0., 2., 4., 6., 8.])


In [56]:
div_term = torch.exp(i * (-math.log(10000.0) / d_model))
div_term

tensor([1.0000e+00, 1.5849e-01, 2.5119e-02, 3.9811e-03, 6.3096e-04])

In [57]:
-math.log(10000.0/1)

-9.210340371976184

In [58]:
pe = torch.zeros(max_length, d_model)

In [59]:
pe

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [71]:
torch.sin(positions * div_term)


tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 8.4147e-01,  1.5783e-01,  2.5116e-02,  3.9811e-03,  6.3096e-04],
        [ 9.0930e-01,  3.1170e-01,  5.0217e-02,  7.9621e-03,  1.2619e-03],
        [ 1.4112e-01,  4.5775e-01,  7.5285e-02,  1.1943e-02,  1.8929e-03],
        [-7.5680e-01,  5.9234e-01,  1.0031e-01,  1.5924e-02,  2.5238e-03]])

In [70]:
torch.cos(positions * div_term)


tensor([[ 1.0000,  1.0000,  1.0000,  1.0000,  1.0000],
        [ 0.5403,  0.9875,  0.9997,  1.0000,  1.0000],
        [-0.4161,  0.9502,  0.9987,  1.0000,  1.0000],
        [-0.9900,  0.8891,  0.9972,  0.9999,  1.0000],
        [-0.6536,  0.8057,  0.9950,  0.9999,  1.0000]])

In [72]:
pe[:,0::2].shape

torch.Size([5, 10])

In [66]:
pe[:,0::2] = torch.sin(positions * div_term)
pe[:,1::2] = torch.sin(positions * div_term)

In [67]:
pe

tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 8.4147e-01,  8.4147e-01,  1.5783e-01,  1.5783e-01,  2.5116e-02,
          2.5116e-02,  3.9811e-03,  3.9811e-03,  6.3096e-04,  6.3096e-04],
        [ 9.0930e-01,  9.0930e-01,  3.1170e-01,  3.1170e-01,  5.0217e-02,
          5.0217e-02,  7.9621e-03,  7.9621e-03,  1.2619e-03,  1.2619e-03],
        [ 1.4112e-01,  1.4112e-01,  4.5775e-01,  4.5775e-01,  7.5285e-02,
          7.5285e-02,  1.1943e-02,  1.1943e-02,  1.8929e-03,  1.8929e-03],
        [-7.5680e-01, -7.5680e-01,  5.9234e-01,  5.9234e-01,  1.0031e-01,
          1.0031e-01,  1.5924e-02,  1.5924e-02,  2.5238e-03,  2.5238e-03]])

## MultiheadAttention

In [73]:
import torch
import torch.nn as nn

In [75]:
B = 2 # batch size
L = 5 # query sequence length (target)
S = 5 # key/value sequence length (source)
E = 8 # embeddign dim
H = 2 # heads


In [76]:
mha = nn.MultiheadAttention(embed_dim=E, num_heads=H, batch_first=True)

In [78]:
query = torch.randn(B,L,E)
key = torch.randn(B,S,E)
value = torch.randn(B,S,E)


In [79]:
output, attn_weights = mha(query, key, value)

In [82]:
attn_weights.shape

torch.Size([2, 5, 5])

In [83]:
attn_weights

tensor([[[0.1929, 0.1762, 0.2398, 0.1949, 0.1962],
         [0.1869, 0.3351, 0.1252, 0.1586, 0.1942],
         [0.1656, 0.1021, 0.3279, 0.2300, 0.1743],
         [0.2648, 0.1925, 0.2490, 0.1107, 0.1830],
         [0.2284, 0.1334, 0.2749, 0.1565, 0.2067]],

        [[0.1631, 0.2259, 0.2216, 0.2159, 0.1735],
         [0.2333, 0.1756, 0.2467, 0.1701, 0.1742],
         [0.2202, 0.1850, 0.2013, 0.1655, 0.2280],
         [0.1504, 0.2597, 0.2485, 0.2349, 0.1065],
         [0.1879, 0.1914, 0.2454, 0.2408, 0.1345]]], grad_fn=<MeanBackward1>)

In [84]:
lengths = torch.tensor([5,3])
key_padding_mask = torch.arange(S).unsqueeze(0) >= lengths.unsqueeze(1)
print("key_padding_mask:\n", key_padding_mask) 

key_padding_mask:
 tensor([[False, False, False, False, False],
        [False, False, False,  True,  True]])


In [87]:
torch.arange(S).unsqueeze(0) 

tensor([[0, 1, 2, 3, 4]])

In [88]:
lengths.unsqueeze(1)

tensor([[5],
        [3]])