In [2]:
import numpy as np

In [12]:
Z=np.array([[[34,44,5],[4,33,67]],[[12,437,6],[9,64,5]]])
Z

array([[[ 34,  44,   5],
        [  4,  33,  67]],

       [[ 12, 437,   6],
        [  9,  64,   5]]])

In [4]:
dim=0

In [5]:
Z.shape

(2, 2, 3)

In [6]:
Z_moved = np.moveaxis(Z, dim,-1)
original_shape = Z_moved.shape 

Z_moved

array([[[ 34,  12],
        [ 44, 437],
        [  5,   6]],

       [[  4,   9],
        [ 33,  64],
        [ 67,   5]]])

In [7]:
Z_moved.shape

(2, 3, 2)

In [13]:
Z

array([[[ 34,  44,   5],
        [  4,  33,  67]],

       [[ 12, 437,   6],
        [  9,  64,   5]]])

In [15]:
Z.swapaxes(0,-1)

array([[[ 34,  12],
        [  4,   9]],

       [[ 44, 437],
        [ 33,  64]],

       [[  5,   6],
        [ 67,   5]]])

In [45]:
key_padding_mask = np.array([[False, False, True, True],   # batch 0
                              [False, True,  True, True]])  # batch 1
# shape (2, 4) = (N=2, S=4)

key_mask = key_padding_mask[:,np.newaxis, np.newaxis,:]
# shape (2, 1, 1, 4) = (N=2, 1, 1, S=4)


In [46]:
key_mask

array([[[[False, False,  True,  True]]],


       [[[False,  True,  True,  True]]]])

In [37]:
key_mask2 = key_padding_mask[:, np.newaxis, np.newaxis, :]

In [43]:
key_mask2.shape

(2, 1, 1, 4)

In [38]:
key_mask

array([[[[False, False,  True,  True],
         [False,  True,  True,  True]]]])

In [39]:
key_mask2

array([[[[False, False,  True,  True]]],


       [[[False,  True,  True,  True]]]])

In [42]:
key_mask

array([[[[False, False,  True,  True],
         [False,  True,  True,  True]]]])

In [50]:
8//3

2